### ISSUE TITLE
Methods for mykrobe lineage calling

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/LemurPaper#15]

**Comment by iqbal-lab** [comment]
i've added text but i'm afraid i've left integrating the two references into the bibliography to you :-(
commit 17a51819760c3cb53d33414d1caf001ceb73fc0e

**Comment by mbhall88** [comment]
If you're happy with https://github.com/mbhall88/LemurPaper/commit/297af64401cd7d784790aec984dedb3455fb8e35 then I think we're done

**Comment by iqbal-lab** [comment]
Yep
